### ISSUE TITLE
Feistel-decrypt.py not found

### ISSUE THREAD

**Issue by SachinMeier** [roFilip/COMP7401-Feistel-Cipher#1]
Hello, 
  This is a helpful and well documented project. However, im unable to find the Feistel-decrypt.py file in src.
I will also be forking this to write it in python3, if you'd like, when im done I can submit a PR so you could have both.

**Comment by filipgutica** [comment]
My bad, that must've been leftover from when there were two files - you can use the feistel.py file for encryption or decryption by setting the -e or -d flags when running

**Comment by SachinMeier** [comment]
Thanks, that's great!
